services:
  neo4j:
    image: neo4j:5.26
    container_name: aura-kg-neo4j

    ports:
      - "7474:7474"
      - "7687:7687"

    environment:
      NEO4J_AUTH: neo4j/password123

    volumes:
      - ./neo4j-data:/data
      - ./graph:/import

    restart: unless-stopped