services:
  neo4j:
    image: neo4j:5.26
    container_name: aura-kg-neo4j

    ports:
      - "7474:7474"
      - "7687:7687"

    environment:
      NEO4J_AUTH: neo4j/password123
      # Tell Neo4j to listen to external traffic on HTTP and Bolt protocols:
      NEO4J_server_default__listen__address: 0.0.0.0
      NEO4J_server_http_listen__address: 0.0.0.0:7474

    volumes:
      - ./neo4j-data:/data
      - ./graph:/import

    restart: unless-stopped